### ISSUE TITLE
hpiR WLS method

### ISSUE THREAD

**Issue by SimonMelamed** [andykrause/hpiR#60]
Hi Andy!

I'm Simon and I'm currently using your package to create a housing index for Stockholm, Sweden, for a school project. I'm wondering why you can't (or don't have to) specify the weights in the rtIndex-function using the estimator "weighted" whereas in the hedonic case, using the hedIndex-function one has to specify weigths when using WLS?

I'd greatly appreciate some clarification for this.

Have a great day,

Simon Melamed

**Comment by andykrause** [comment]
Simon:  Thanks for reaching out.  The weighted option for repeat transaction (rt) or weighted repeat sales approach defaults to the weighting proposed by Case and Shiller (http://www.econ.yale.edu/~shiller/pubs/p0781.pdf; https://www.nber.org/papers/w2393.pdf).  You can add other weighting, but if you don't this default is used.  Since there is no default for WLS in the hedIndex approach you must supply them if you hope to run a weighted model.  

Perhaps I should clarify this in the documentation for my next release.

Thank you for reaching out and let me know if you have any other questions.

**Comment by SimonMelamed** [comment]
Hi Andy,

Thank you for your answer.

I was also wondering if you could provide a reference to which theory the Robust estimator was based upon?

Also, when I created my Repeat Sales index, the OLS and WLS hedonic time dummy index was identical, is that normal?

Greatly appreciate any answers. Hope you have a nice day.

Best regards,

Simon Melamed

**Comment by SimonMelamed** [comment]
Hello Andy, 

I hope you can answer a question of mine. 

When I try to create a WLS hedonic index using the hedIndex and attempt to use expenditure shares as weights, 
I get the error,
 
'You have supplied a set of weights that do not match the data.Model being run in base OLS format.’,
Do you know why this is?

Best regards,

Simon Melamed

**Comment by andykrause** [comment]
Simon:  Actually, I see the problem.  If you use the wrapper function (`hedIndex`) and some of the records are removed due to having two sales of same property in the same period (mostly likely if using a annual or quarterly periodicity), then the weights will be the wrong length.  Its a bug on my end.  Thanks for bringing to my attention.

**Comment by andykrause** [comment]
Simon: Implemented a fix here.  `remotes::install_github("andykrause/hpiR")` should get you the fixed version.  I'll push this update to CRAN with my next version update.

Thanks for reporting the bug!
